### PR TITLE
Documentation for the `HTTPoison` and `HTTPoison.Base` modules

### PR DESCRIPTION
**Pull request by whatyouhide**
I added a `@moduledoc` to the `HTTPoison.Base` module which describes all the overridable functions and how the `Base` module can be used to wrap HTTPoison. I also added some documentation to the `HTTPoison` module.

Let me know if I can do anything else!

### CODE REVIEW

**Comment by edgurgel** [comment]
This is great! :+1: 

Again, thank you very much for your work. I should add you to the list of contributors! :)

**Comment by whatyouhide** [comment]
Happy to help :). I'm trying to make the docs shine before maybe helping with code/features, but let me know if I can help with something specific!

**Comment by edgurgel** [comment]
I was wondering if it was a good idea to have pretty much every hackney option available through HTTPoison, at least the ones that are not specific to hackney(like pool size). The ones I have in my mind: cookies, basic_auth. What do you think?

**Comment by whatyouhide** [comment]
@edgurgel I'm gonna read a bit more about hackney today and I'll get back to you, ok? :)

**Comment by edgurgel** [comment]
Sure, no hurry. You can see we have tests for some of these options but they need to go through the `hackney` keyword, I think we can support some of them directly and just translate to hackney.

**Pull request merged**
