### PR TITLE
Add the request!/1 function

### PR DESCRIPTION
**Pull request by GuillaumeMilan**
The `request!/1` request was missing from the repository

### CODE REVIEW

**Comment by edgurgel** [comment]
Thanks! Would you mind adding some tests? Cheers!

**Comment by GuillaumeMilan** [comment]
> Thanks! Would you mind adding some tests? Cheers!

Added some tests.
But as the request function didn't had one I don't really know you want me to test (what is common between request and the other functions in the engine?)

**Review by edgurgel — APPROVED** [review]

**Comment by edgurgel** [comment]
Tests are good! We just need to `mix format` it now

**Comment by GuillaumeMilan** [comment]
Sorry I don't have the reflexe to trigger it 
Done 👍

**Pull request merged**
