### PR TITLE
Accept ssl_options for the Hackney library. 

### PR DESCRIPTION
**Pull request by thurtt**
This will allow the use of certificate based authentication as well as other things. The options are the same as the options used in the erlang ssl module.

I did not add any tests for the options since there were no ssl specific ones in the current suite of tests. Thanks for creating a very elegant and useful library.

### CODE REVIEW

**Comment by edgurgel** [comment]
Thanks for the contribution. Could you rebase with latest master? :+1:

**Comment by thurtt** [comment]
I've got the code rebased and the unit tests are passing unit tests on my end. Please let me know if you need me to do anything else.

**Comment by edgurgel** [comment]
It's "unmergeable" and the commits of the PR include more than 1 commit. I can commit this change directly to master if you want.

**Comment by thurtt** [comment]
I guess I must have screwed up the rebase somehow. Maybe just committing the change directly to master would be the simplest solution.

**Comment by edgurgel** [comment]
I just add the `ssl` option: https://github.com/edgurgel/httpoison/commit/2637f6684d132cc02d1b7f18332dc1d7f8d98e1b

I will generate a new minor version soon with this feature. Thanks! :+1:

**Comment by thurtt** [comment]
Awesome! This will be very helpful to us. Thanks again. :grinning:

**Pull request closed without merging**
