### PR TITLE
correct :max_body_length documentation and spec

### PR DESCRIPTION
**Pull request by pedep**
I'm sorry, but it seems #354's assumed behaviour was wrong.
I assumed the `:max_length` in `body/2` would error, because, what would an incomplete response be worth, but it seems it simply returns the body up until `:max_length`.

I have corrected the doc and spec to reflect this.
I will submit another PR implementing this behaviour in HTTPoison, since my original intention was to protect against too much data being returned with an error.

Sorry for the mistake @edgurgel

### CODE REVIEW

**Comment by pedep** [comment]
I'm busy tonight, but i'll see if i can write a quick test tomorrow

**Comment by edgurgel** [comment]
No problem, @pedep ! I will probably have some free time this weekend. I can write the test if you couldn't find time 👍

**Comment by pedep** [comment]
@edgurgel I've dug a bit, and i think this spec explains & covers the expected behavior of our usage of `:hackney.body/2`

**Comment by edgurgel** [comment]
@pedep, fantastic!

**Pull request merged**
