### PR TITLE
Add temporary note about ssl issue with Erlang 19

### PR DESCRIPTION
**Pull request by Ch4s3**
I think it would be nice to temporarily add a note about fixing this ssl error https://github.com/edgurgel/httpoison/issues/164 in the readme. Thoughts?

### CODE REVIEW

**Comment by edgurgel** [comment]
Thanks!

**Comment by Ch4s3** [comment]
Nbd! I'll keep an eye out and try to remove it when the Erlang issue gets fixed.

**Comment by jbrowning** [comment]
The referenced Erlang issue was marked as Resolved: Not a Bug in August. Looks like there's some 👈 👉 going on.

**Comment by Ch4s3** [comment]
@jbrowning If you could think of a more neutral/accurate message, I'll happily amend it.

**Pull request merged**
